(function () {
  "use strict";

  window.FONT_TAGS = {
    "1Row": ["line"],
    "3-D": ["shadow","block"],
    "3D Diagonal": ["shadow","slant","block"],
    "3D-ASCII": ["shadow","block"],
    "3x5": ["filled"],
    "4Max": ["filled","readable"],
    "5 Line Oblique": ["slant","block"],
    "Acrobatic": ["graphic","filled"],
    "Alligator": ["slant","filled"],
    "Alligator2": ["filled"],
    "Alpha": ["readable","block"],
    "Alphabet": ["readable"],
    "AMC 3 Line": ["line"],
    "AMC 3 Liv1": ["sideways"],
    "AMC AAA01": ["filled"],
    "AMC Neko": ["filled"],
    "AMC Razor": ["graphic","block"],
    "AMC Razor2": ["graphic","block"],
    "AMC Slash": ["filled"],
    "AMC Slider": ["line"],
    "AMC Thin": ["bubble"],
    "AMC Tubes": ["filled"],
    "AMC Untitled": ["bubble"],
    "ANSI Regular": ["readable","filled"],
    "ANSI Shadow": ["shadow","filled","readable"],
    "Arrows": ["graphic","filled"],
    "ASCII New Roman": ["calligraphy","line"],
    "Avatar": ["bubble","block"],
    "B1FF": ["line"],
    "Banner": ["readable","filled"],
    "Banner3": ["readable","filled"],
    "Banner3-D": ["shadow","readable","filled","wall"],
    "Banner4": ["readable","filled","wall"],
    "Barbwire": ["graphic","filled"],
    "Basic": ["readable","block"],
    "Bear": ["graphic"],
    "Bell": ["readable","line"],
    "Benjamin": ["readable","line"],
    "Big": ["readable","block"],
    "Big Chief": ["line"],
    "Big Money-ne": ["graphic","block"],
    "Big Money-nw": ["graphic","block"],
    "Big Money-se": ["graphic","block"],
    "Big Money-sw": ["graphic","block"],
    "Bigfig": ["line"],
    "Binary": ["utility"],
    "Block": ["block","filled"],
    "Blocks": ["block","graphic"],
    "Bloody": ["graphic"],
    "Bolger": ["readable","filled"],
    "Braced": ["bubble"],
    "Bright": ["readable","filled","wall"],
    "Broadway": ["graphic","filled"],
    "Broadway KB": ["block"],
    "Bubble": ["graphic"],
    "Bulbhead": ["bubble"],
    "Caligraphy": ["calligraphy"],
    "Caligraphy2": ["calligraphy"],
    "Calvin S": ["graphic","filled"],
    "Cards": ["graphic"],
    "Catwalk": ["filled","shadow"],
    "Chiseled": ["graphic","block"],
    "Chunky": ["block"],
    "Coinstak": ["filled"],
    "Cola": ["graphic","calligraphy"],
    "Colossal": ["readable","filled"],
    "Computer": ["readable","filled"],
    "Contessa": ["calligraphy","line"],
    "Contrast": ["wall","filled"],
    "Cosmike": ["graphic","filled"],
    "Crawford": ["readable","bubble"],
    "Crawford2": ["readable","bubble"],
    "Crazy": ["graphic","block"],
    "Cricket": ["readable","bubble"],
    "Cursive": ["calligraphy","line"],
    "Cyberlarge": ["line"],
    "Cybermedium": ["line"],
    "Cybersmall": ["readable","line"],
    "Cygnet": ["line"],
    "DANC4": ["graphic"],
    "Dancing Font": ["graphic"],
    "Decimal": ["utility"],
    "Def Leppard": ["filled"],
    "Delta Corps Priest 1": ["filled"],
    "Diamond": ["filled"],
    "Diet Cola": ["line","calligraphy"],
    "Digital": ["readable","line"],
    "Doh": ["block","filled"],
    "Doom": ["block"],
    "DOS Rebel": ["filled","shadow","block"],
    "Dot Matrix": ["readable"],
    "Double": ["block"],
    "Double Shorts": ["block"],
    "Dr Pepper": ["block"],
    "DWhistled": ["graphic"],
    "Efti Chess": ["graphic","abstract"],
    "Efti Font": ["block"],
    "Efti Italic": ["slant","block"],
    "Efti Piti": ["filled"],
    "Efti Robot": ["graphic","block"],
    "Efti Wall": ["graphic","wall"],
    "Efti Water": ["block"],
    "Electronic": ["filled","readable"],
    "Elite": ["filled"],
    "Epic": ["block"],
    "Fender": ["filled"],
    "Filter": ["filled","readable"],
    "Fire Font-k": ["graphic","block"],
    "Fire Font-s": ["graphic","block"],
    "Flipped": ["sideways","block"],
    "Flower Power": ["graphic","block"],
    "Four Tops": ["line","readable"],
    "Fraktur": ["blackletter","filled"],
    "Fun Face": ["graphic","bubble"],
    "Fun Faces": ["graphic","bubble"],
    "Fuzzy": ["block","bubble"],
    "Georgi16": ["filled","readable"],
    "Georgia11": ["filled","readable"],
    "Ghost": ["graphic","bubble","readable"],
    "Ghoulish": ["graphic","block"],
    "Glenyn": ["block","readable"],
    "Goofy": ["block"],
    "Gothic": ["blackletter","block"],
    "Graceful": ["bubble"],
    "Gradient": ["wall"],
    "Graffiti": ["bubble"],
    "Greek": ["block"],
    "Heart Left": ["graphic"],
    "Heart Right": ["graphic"],
    "Henry 3D": ["shadow","block"],
    "Hex": ["utility"],
    "Hieroglyphs": ["graphic","abstract"],
    "Hollywood": ["line","calligraphy"],
    "Horizontal Left": ["sideways","block"],
    "Horizontal Right": ["sideways","block"],
    "ICL-1900": ["graphic","utility"],
    "Impossible": ["graphic","block"],
    "Invita": ["calligraphy","line"],
    "Isometric1": ["graphic","block"],
    "Isometric2": ["graphic","block"],
    "Isometric3": ["graphic","block"],
    "Isometric4": ["graphic","block"],
    "Italic": ["slant","calligraphy"],
    "Ivrit": ["reversed","block"],
    "Jacky": ["block"],
    "Jazmine": ["wall"],
    "Jerusalem": ["reversed","block"],
    "JS Block Letters": ["block"],
    "JS Bracket Letters": ["bubble","readable"],
    "JS Capital Curves": ["calligraphy","line"],
    "JS Cursive": ["calligraphy","line"],
    "JS Stick Letters": ["line","readable"],
    "Katakana": ["abstract","filled"],
    "Kban": ["block","filled"],
    "Keyboard": ["graphic"],
    "Knob": ["sideways","block"],
    "Konto": ["filled"],
    "Konto Slant": ["slant","line"],
    "Larry 3D": ["shadow","block","readable"],
    "Larry 3D 2": ["shadow","block"],
    "LCD": ["line","readable"],
    "Lean": ["slant","shadow","readable"],
    "Letters": ["readable","filled"],
    "Lil Devil": ["graphic","block"],
    "Line Blocks": ["block","readable"],
    "Linux": ["bubble"],
    "Lockergnome": ["filled","shadow"],
    "Madrid": ["line"],
    "Marquee": ["filled"],
    "Maxfour": ["line"],
    "Merlin1": ["bubble"],
    "Merlin2": ["bubble","block"],
    "Mike": ["line"],
    "Mini": ["readable","line"],
    "Mirror": ["reversed","block"],
    "Mnemonic": ["broken"],
    "Modular": ["block","readable"],
    "Morse": ["utility"],
    "Morse2": ["utility"],
    "Moscow": ["filled"],
    "Mshebrew210": ["abstract"],
    "Muzzle": ["line"],
    "Nancyj": ["filled"],
    "Nancyj-Fancy": ["filled"],
    "Nancyj-Improved": ["filled"],
    "Nancyj-Underlined": ["filled"],
    "Nipples": ["graphic","shadow"],
    "NScript": ["calligraphy","filled"],
    "NT Greek": ["bubble"],
    "NV Script": ["calligraphy","filled"],
    "O8": ["filled","readable"],
    "Octal": ["utility"],
    "Ogre": ["block"],
    "Old Banner": ["filled"],
    "OS2": ["wall","readable"],
    "Pagga": ["wall","shadow","readable"],
    "Patorjk-HeX": ["block","readable"],
    "Patorjk's Cheese": ["graphic","block"],
    "Pawp": ["graphic","block"],
    "Peaks": ["shadow","filled"],
    "Peaks Slant": ["slant","wall","graphic"],
    "Pebbles": ["graphic","filled"],
    "Pepper": ["line","slant"],
    "Poison": ["graphic","filled"],
    "Puffy": ["bubble"],
    "Puzzle": ["graphic"],
    "Pyramid": ["graphic"],
    "Rammstein": ["graphic","block"],
    "Rectangles": ["bubble"],
    "Red Phoenix": ["block"],
    "Relief": ["shadow","wall"],
    "Relief2": ["shadow","wall"],
    "Reverse": ["filled","wall","readable"],
    "Roman": ["readable","filled"],
    "Rot13": ["abstract"],
    "Rotated": ["sideways","line"],
    "Rounded": ["bubble","graphic"],
    "Rowan Cap": ["filled","slant"],
    "Rozzo": ["filled"],
    "Runic": ["abstract"],
    "Runyc": ["abstract"],
    "S Blood": ["filled"],
    "Santa Clara": ["line","slant"],
    "Script": ["calligraphy","line"],
    "Serifcap": ["bubble","block"],
    "Shadow": ["shadow","block"],
    "Shimrod": ["line"],
    "Short": ["readable","line"],
    "SL Script": ["calligraphy","line"],
    "Slant": ["slant","block","readable"],
    "Slant Relief": ["slant","shadow","wall"],
    "Slide": ["filled"],
    "Small": ["readable","block"],
    "Small Caps": ["block"],
    "Small Isometric1": ["graphic","block"],
    "Small Keyboard": ["graphic"],
    "Small Poison": ["filled"],
    "Small Script": ["calligraphy","line"],
    "Small Shadow": ["shadow","block"],
    "Small Slant": ["slant","block","readable"],
    "Small Tengwar": ["line"],
    "Soft": ["bubble"],
    "Speed": ["slant","readable"],
    "Spliff": ["bubble"],
    "Stacey": ["block"],
    "Stampate": ["line","calligraphy"],
    "Stampatello": ["line","calligraphy"],
    "Standard": ["readable","block"],
    "Star Strips": ["graphic","filled"],
    "Star Wars": ["block"],
    "Stellar": ["shadow","filled"],
    "Stforek": ["block"],
    "Stick Letters": ["line","readable"],
    "Stop": ["block"],
    "Straight": ["readable","line"],
    "Stronger Than All": ["block"],
    "Sub-Zero": ["graphic","block"],
    "Swamp Land": ["block","graphic"],
    "Swan": ["line","calligraphy"],
    "Sweet": ["bubble"],
    "Tanja": ["filled"],
    "Tengwar": ["filled"],
    "Term": ["readable","line"],
    "Test1": ["graphic","block"],
    "The Edge": ["graphic","filled"],
    "Thick": ["filled"],
    "Thin": ["line","readable"],
    "THIS": ["graphic","filled"],
    "Thorned": ["line"],
    "Three Point": ["line","readable"],
    "Ticks": ["graphic","wall"],
    "Ticks Slant": ["graphic","slant","wall"],
    "Tiles": ["graphic","block"],
    "Tinker-Toy": ["graphic","line"],
    "Tombstone": ["graphic","line"],
    "Train": ["graphic","block"],
    "Trek": ["graphic","filled","slant"],
    "Tsalagi": ["abstract","line"],
    "Tubular": ["graphic","filled"],
    "Twisted": ["graphic","block"],
    "Two Point": ["line","readable"],
    "Univers": ["readable","filled"],
    "USA Flag": ["graphic","filled"],
    "Varsity": ["block"],
    "Wavy": ["line"],
    "Weird": ["line"],
    "Wet Letter": ["graphic","block"],
    "Whimsy": ["graphic","filled"],
    "Wow": ["block"]
  };
})();
